<a href="https://colab.research.google.com/github/nefetorve/big_data/blob/master/01_wprowadzenie/02_algebra_liniowa_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

Norma wektora w przestrzeni R2

In [4]:
v1 = np.array([-1,4])
v1

array([-1,  4])

In [5]:
np.linalg.norm(v1) # długość wektora

4.123105625617661

Norma euklidesowa w Rn

In [6]:
v2 = np.array([-10,10,13])
np.linalg.norm(v2)

19.209372712298546

Odległość dwóch punktów na płaszczyźnie

In [7]:
p = np.array([3,0])
q = np.array([0,4])

np.linalg.norm(p-q)

5.0

Odległość dwóch punktów przestrzeni Rn

In [8]:
p = np.array([3,0,2])
q = np.array([0,4,5])

np.linalg.norm(p-q)

5.830951894845301

Macierze

In [9]:
X = np.array([[5,3],[3,9]])
Y = np.array([[1],[-1]])
print(X, '\n')
print(Y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [10]:
Z = np.dot(X,Y)
Z

array([[ 2],
       [-6]])

In [11]:
Z.shape

(2, 1)

2 przykład

In [12]:
X = np.array([[2,-1,3],
              [3,1,0]])
Y = np.array([[2,1,-1],
              [0,-1,2],
              [3,2,0]])


In [13]:
print(X, '\n')
print(Y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [14]:
Z = np.dot(X,Y)

array([[13,  9, -4],
       [ 6,  2, -1]])

In [16]:
Z.shape

(2, 1)

Wyznacznik macierzy

In [17]:
A = np.array([[2,4],[-1,3]])
np.linalg.det(A)

9.999999999999998

Ślad macierzy

In [19]:
np.trace(Y)

1

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

macierz odwrotna

In [21]:
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [22]:
np.dot(A,B)

array([[1.00000000e+00, 0.00000000e+00],
       [2.77555756e-17, 1.00000000e+00]])

In [23]:
np.dot(B,A)

array([[ 1.00000000e+00, -1.11022302e-16],
       [ 0.00000000e+00,  1.00000000e+00]])

In [27]:
np.set_printoptions(precision=2,suppress=True)

np.dot(A,B)

array([[1., 0.],
       [0., 1.]])

Macierz transponowana

In [28]:
A.T

array([[ 2, -1],
       [ 4,  3]])

Rozwiązywanie układów równań 

In [30]:
A = np.array([[2,4],[1,-1]])
print(A)

[[ 2  4]
 [ 1 -1]]


In [31]:
B = np.array([[10],[-1]])
print(B)

[[10]
 [-1]]


In [32]:
A_inv =np.linalg.inv(A)

In [33]:
X = np.dot(A_inv,B)

In [34]:
X

array([[1.],
       [2.]])

In [35]:
X.shape

(2, 1)