<a href="https://colab.research.google.com/github/nefetorve/big_data/blob/master/01_wprowadzenie/funkcje_statystyczne.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.__version__

'1.18.5'

In [6]:
price = np.array([[12.40,12.8,11.9, 12.6, 1000],
                  [12.5,13,11.7,12.2,2000],
                  [12.2,13.4,12.2,13.2,1500]])

In [7]:
print(price)

[[  12.4   12.8   11.9   12.6 1000. ]
 [  12.5   13.    11.7   12.2 2000. ]
 [  12.2   13.4   12.2   13.2 1500. ]]


In [8]:
price.sum()

4650.1

In [9]:
sum(price)

array([  37.1,   39.2,   35.8,   38. , 4500. ])

In [11]:
price.sum(axis=0) #sumowanie po kolumnie

array([  37.1,   39.2,   35.8,   38. , 4500. ])

In [13]:
price.sum(axis=1) #sumowanie po wierszach

array([1049.7, 2049.4, 1551. ])

In [14]:
np.sum(price)

4650.1

In [20]:
np.min(price) # minimum z całej tablicy

11.7

In [17]:
np.min(price, axis = 0) # minimum w każdej kolumnie

array([  12.2,   12.8,   11.7,   12.2, 1000. ])

In [21]:
np.set_printoptions(4,suppress=True)

In [22]:
np.std(price,axis=0)

array([  0.1247,   0.2494,   0.2055,   0.411 , 408.2483])

In [23]:
np.var(price,axis=0)

array([     0.0156,      0.0622,      0.0422,      0.1689, 166666.6667])