<a href="https://colab.research.google.com/github/nefetorve/big_data/blob/master/051_060_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

### Spis treści:
* [Import biblioteki](#0)
* [Ćwiczenie 51](#1)
* [Ćwiczenie 52](#2)
* [Ćwiczenie 53](#3)
* [Ćwiczenie 54](#4)
* [Ćwiczenie 55](#5)
* [Ćwiczenie 56](#6)
* [Ćwiczenie 57](#7)
* [Ćwiczenie 58](#8)
* [Ćwiczenie 59](#9)
* [Ćwiczenie 60](#10)

### <a name='0'></a>Import biblioteki

In [1]:
import numpy as np

np.random.seed(42)
np.__version__

'1.18.5'

### <a name='1'></a> Ćwiczenie 51
Podane są poniżej dwie tablice $A$ i $B$:


```
A = np.array([[3, 4, 5],
              [8, 3, 1]])
B = np.array([[0, 5, 2],
              [4, 2, 1]])
```
* Połącz te tablice w następujący sposób:


```
array([[3, 4, 5],
       [8, 3, 1],
       [0, 5, 2],
       [4, 2, 1]])
```
__Wskazówka:__ Wykorzystaj funkcję _np.concatenate()_.





In [ ]:
# tutaj wpisz rozwiązanie

* Połącz te tablice w następujący sposób:


```
array([[3, 4, 5, 0, 5, 2],
       [8, 3, 1, 4, 2, 1]])
```
__Wskazówka:__ Wykorzystaj funkcję _np.concatenate()_.

In [ ]:
# tutaj wpisz rozwiązanie

### <a name='2'></a> Ćwiczenie 52
Podana jest tablica zawierająca dane _data_ oraz tablica zawierająca docelową klasę dla danego wiersza _target_:

```
data = np.array([[4.3, 4.2],
                 [3.1, 3.6]])
target = np.array([[0],
                   [1]])
```



Połącz te tablice w jedną tak jak pokazano poniżej:


```
array([[4.3, 4.2, 0. ],
       [3.1, 3.6, 1. ]])
```



In [ ]:
# tutaj wpisz rozwiązanie

### <a name='3'></a> Ćwiczenie 53
Podane są trzy poniższe jednowymiarowe tablice:  


```
feature1 = np.array([1.6, 0.9, 2.2])
feature2 = np.array([0.4, 1.3, 3.2])
feature3 = np.array([1.4, 0.3, 1.2])
```
Przekształć każdą z tych tablic w kolumnę i sklej w jedną dużą tablicę.

__Oczekiwany wynik:__


```
array([[1.6, 0.4, 1.4],
       [0.9, 1.3, 0.3],
       [2.2, 3.2, 1.2]])
```

__Wskazówka:__ Wykorzystaj funkcję _np.column_stack()_.



In [ ]:
# tutaj wpisz rozwiązanie

### <a name='4'></a> Ćwiczenie 54
Podana jest poniższa dwuwymiarowa tablica:

```
A = np.random.randint(low=0, high=7, size=(5, 8))
A[:, :2] = 0
A[:, -2:] = 1
A
```
```
array([[0, 0, 4, 6, 2, 4, 1, 1],
       [0, 0, 6, 2, 2, 4, 1, 1],
       [0, 0, 1, 3, 5, 5, 1, 1],
       [0, 0, 3, 1, 5, 4, 1, 1],
       [0, 0, 2, 6, 1, 3, 1, 1]])
```

Podziel tablicę na 3 części tak aby pierwsze dwie kolumny stanowiły pierwszą tablicę $A1$, cztery kolejne drugą tablicę $A2$ oraz dwie ostatnie trzecią tablicę $A3$.

__Wskazówka:__ Wykorzystaj funkcję _np.split()_.

In [ ]:
# tutaj wpisz rozwiązanie

### <a name='5'></a> Ćwiczenie 55
Podana jest poniższa tablica $A$:

```
A = np.random.randint(low=0, high=2, size=(10, 6))
```
Wyznacz łączną liczbę elementów niezerowych dla tej tablicy.

__Wskazówka:__ Wykorzystaj funkcję _np.count_nonzero()_.


In [ ]:
# tutaj wpisz rozwiązanie

Wyznacz łączną liczbę elementów niezerowych dla każdego wiersza tej tablicy.

__Wskazówka:__ Wykorzystaj funkcję _np.count_nonzero()_.

In [ ]:
# tutaj wpisz rozwiązanie

### <a name='6'></a> Ćwiczenie 56
Poniżej podana jest przykładowa tablica $A$:

```
A = np.random.randn(10, 4)
```

```
array([[-0.53441645, -1.49505387, -0.78925833,  0.74371128],
       [-0.21216142, -0.42686879,  0.50144833,  1.15818665],
       [ 0.25711687,  0.3145129 ,  1.37186213,  0.17555329],
       [-0.30928855,  0.6731255 , -0.25663018, -0.36782572],
       [ 1.27373362, -0.29195267, -2.65517605,  0.34551794],
       [-0.39551645, -0.28913686,  0.45293633, -0.16606091],
       [ 0.21493883, -2.02231493, -0.94305681,  1.40395874],
       [-0.0185508 , -1.67350462, -1.07253183, -0.99258618],
       [ 0.10234768, -0.43260928, -0.6591823 ,  0.0039373 ],
       [ 0.4777541 , -0.25902864, -0.57470921, -0.42149822]])
```


Ustaw odopowiednią opcję biblioteki numpy pozwalającą drukować tablice z określoną precyzją. Ustaw jej wartość na 4 i wydrukuj tablicę $A$.



In [ ]:
# tutaj wpisz rozwiązanie

### <a name='7'></a> Ćwiczenie 57
Podana jest poniższa tablica numpy $A$:

```
A = np.array([1.2e-6, 1.7e-7])
```

Ustaw wartość precyzji na 8. Następnie ustaw odopowiednią opcję biblioteki numpy pozwalającą stłumić notację wykładniczą. Wydrukuj tablicę $A$.

__Oczekiwany wynik:__


```
array([0.0000012 , 0.00000017])
```





In [ ]:
# tutaj wpisz rozwiązanie

### <a name='8'></a> Ćwiczenie 58
Podana jest poniższa tablica numpy $A$:

```
A = np.random.randn(8, 4)
```
Usuń trzecią kolumnę z tablicy $A$.

__Oczekiwany wynik:__


```
array([[-0.55692881, -0.66003196,  0.70856031],
       [ 0.22378737, -0.19796576, -0.16889332],
       [ 0.26062786,  0.29865445, -0.92259267],
       [-2.40317659,  1.79961876, -1.96495796],
       [ 0.13051561, -1.7085185 ,  0.54885043],
       [ 1.77268727,  0.38751181, -0.05141955],
       [-1.80858596, -0.45075211,  0.15332866],
       [ 1.94218961, -1.93679529, -1.83350954]])
```
__Wskazówka:__ Wykorzystaj funkcję _np.delete()_.




In [ ]:
# tutaj wpisz rozwiązanie

### <a name='9'></a> Ćwiczenie 59
Podana jest tablica jednowymiarowa $v$ (wektor):

```
v = np.array([3, 4, -2])
```
Policz normę wektora $v$.


In [ ]:
# tutaj wpisz rozwiązanie

### <a name='10'></a> Ćwiczenie 60
Poniżej podana jest przykładowa tablica $A$:


```
A = np.random.randint(10, size=(100, 30))
```
Ustaw odopowiednią opcję biblioteki numpy pozwalającą drukować 10 skrajnych elementów. Wydrukuj tablicę $A$.


In [ ]:
# tutaj wpisz rozwiązanie