<a href="https://colab.research.google.com/github/nefetorve/big_data/blob/master/numPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
 import numpy as np

In [3]:
np.__version__ #sprawdzenie wersji biblioteki numpy

'1.18.5'

In [4]:
print(dir(np)) # sprawdzenie wszystkich funkcji w bibliotece np

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytesttester', 'abs', 'absolute', 'absolute_import

In [5]:
help(np.array) # sprawdzenie jak działa funkcja

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly crea

**1D Array** - tworzenie tablicy jednowymiarowej


In [6]:
x = np.array([1,3])
x

array([1, 3])

In [7]:
print(x)  

[1 3]


In [8]:
type(x) # sprawdzenie typu zmiennej

numpy.ndarray

In [9]:
x.ndim #wymiar tablicy

1

In [10]:
x.shape #kształt tablicy

(2,)

In [11]:
x.size #liczba elementów tablicy

2

In [12]:
x.dtype #typ danych (ile miejsca zajmują w pamięci?)

dtype('int64')

Liczby zmiennoprzecinkowe

In [13]:
x = np.array([1.3,2.3,1.4])
print(x)

[1.3 2.3 1.4]


In [14]:
x.dtype

dtype('float64')

**2D array**


In [15]:
x = np.array([[1,2],[-3,1]])

In [16]:
x.ndim

2

In [17]:
x.shape

(2, 2)

In [18]:
x.dtype

dtype('int64')

In [19]:
x = np.array([[1,2,4],[4,2,1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [20]:
x.ndim

2

In [21]:
x.shape

(2, 3)

3D Array

In [22]:
x = np.array(
   [
    [
     [4,3,1],
     [3,1,2]
     ],
     [
      [4,1,3],
      [4,2,1]
      ],
      [
      [4,1,3],
      [4,2,1]
      ]
    ])
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [23]:
x.ndim

3

In [24]:
x.shape

(3, 2, 3)

**Typy danych**


In [25]:
A = np.array([1,2,3])
A.dtype

dtype('int64')

In [26]:
A = np.array([1.,2.7,3.])
A.dtype

dtype('float64')

In [27]:
A = np.array([1,2,3], dtype='complex')
A

array([1.+0.j, 2.+0.j, 3.+0.j])

In [28]:
A = np.array([True, False])
A.dtype

dtype('bool')

**Tworzenie tablicy**


In [29]:
np.zeros(shape=(4,10), dtype='int') #wypełnij 0    

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [30]:
np.ones(shape=(5,5),dtype='complex') # wypełnij 1 

array([[1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j]])

In [31]:
np.full(shape=(3,3), fill_value=4,dtype="int") #wypełnij 4 (dowolną wartością)

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [32]:
 np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.arange(start=5,stop=10, step=2)

array([5, 7, 9])

In [34]:
np.linspace(start=0,stop=1,num=5) #równo rozkłada przedział na liczbę elementów

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [35]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [36]:
A.reshape((-1,5)) # zmienia rozmiar tablicy

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

**Operacje na tablicach**

In [37]:
A = np.array([3,1,4,2])
B = np.array([3,-1,3,2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [38]:
A + B


array([6, 0, 7, 4])

In [39]:
A - B

array([0, 2, 1, 0])

In [40]:
A * B #Ax * Bx, Ay * By ...

array([ 9, -1, 12,  4])

In [41]:
A/B # po dzieleniu jest float

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [42]:
A + 3 #dodanie stałej do każdeego elementu

array([6, 4, 7, 5])

In [43]:
2 * A 

array([6, 2, 8, 4])

In [44]:
np.add(A,B)

array([6, 0, 7, 4])

Mnożenie macierzowe 

In [45]:
X = np.array([[1,3],[-2,0]]) 
Y = np.array([[6,0],[-1,2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [46]:
np.dot(X,Y)

array([[  3,   6],
       [-12,   0]])

Generowanie liczb pseudolowosych

In [47]:
np.random.seed(0) #ustalenie ziarna losowania 

In [48]:
np.random.randn() #losowa wartość z rozkładu normalnego 

1.764052345967664

In [49]:
np.random.randn(10) #10 wartości losowych z rozkładu normalnego 

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [50]:
np.random.randn(10,4) #do utworzenia histogramu rozkładu normalnego; wartości utożsamiane jako 10 (liczba próbek), 4 (liczba zmiennych)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [51]:
np.random.rand() # wartość losowa z przedziału [0,1) - rozkład jednostajny

0.1965823616800535

In [52]:
np.random.randint(10) #liczba całkowita mniejsza niż 10 

0

In [55]:
np.random.randint(low=10, high=101, size=10) #size -> rozmiar generowanych danych

array([10, 20, 53, 68, 33, 69, 12, 72, 45, 77])

In [56]:
np.random.choice([4,2,1,3]) # metoda choice zwraca losowy element z listy

1

In [57]:
np.random.choice(["Kuba", "Aga", "Chico"]) # metoda choice zwraca losowy element z listy

'Chico'

In [59]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
np.random.shuffle(data) # przetasowanie elementów na stałe

In [63]:
data

array([0, 9, 3, 7, 5, 1, 8, 6, 4, 2])

Podstawowe funkcje

In [64]:
np.exp(1)

2.718281828459045

In [66]:
np.sqrt(9) 

3.0

In [75]:
np.all([2,3,0]) # Czy zwraca wartość False/True? Jeżeli wystąpi chociaż jedno 0, to false.

False

In [76]:
np.any([1,2,3])

True

In [71]:
np.any([0,0,0])

False

In [73]:
bool(-1)

True

In [78]:
A = np.random.rand(5)
A

array([0.36980809, 0.14644176, 0.56961841, 0.70373728, 0.28847644])

In [79]:
np.argmax(A) # zwraca index, gdzie największa wartość

3

In [80]:
A[np.argmax(A)]

0.7037372792899163

In [81]:
np.max(A)

0.7037372792899163

In [82]:
np.argmin(A)

1

In [90]:
np.argsort(A) # sortowanie rosnąco indeksów

array([1, 4, 0, 2, 3])

In [93]:
np.mean(A) # średnia

0.4156163955478408

In [94]:
np.median(A) # mediana

0.36980809274834003

In [95]:
np.std(A) # odchylenie standardowe

0.19872001180237212

Indeksowanie

In [96]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [97]:
#A[idx], A[start:stop], A[:stop], A[start:]

In [99]:
A[2]

2

In [101]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [102]:
A[:2]

array([0, 1])

In [103]:
A[-1]

19

In [105]:
A = A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [106]:
 A[0] # wycinanie wiersza

array([0, 1, 2, 3, 4])

In [107]:
A[:,0] # wycinanie kolumny

array([ 0,  5, 10, 15])

In [108]:
A[:,-1] # wycinanie ostatniej kolumny

array([ 4,  9, 14, 19])

In [109]:
A[1,1] # wycinanie konkretnego elementu

6

In [110]:
A[1:3,1:4] # wycinanie kawałka

array([[ 6,  7,  8],
       [11, 12, 13]])

In [111]:
A[1,2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [114]:
for row in A:
  print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [116]:
for item in A.flat:
  print(item) # iterowanie po każdym elemencie tablicy

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


Zmiana rozmiaru tablic

In [117]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [118]:
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [121]:
A.ravel() # wypłaszczenie

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [122]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

Maski logiczne

In [136]:
A = np.arange(start=-10,stop=10,step=0.5)
A= A.reshape(10,-1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [137]:
A > 0 

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [140]:
np.bitwise_and(A>0,A<5) 

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])