<a href="https://colab.research.google.com/github/nefetorve/big_data/blob/master/numPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
np.__version__ #sprawdzenie wersji biblioteki numpy

'1.18.5'

In [ ]:
print(dir(np)) # sprawdzenie wszystkich funkcji w bibliotece np

In [ ]:
help(np.array) # sprawdzenie jak działa funkcja

**1D Array** - tworzenie tablicy jednowymiarowej


In [8]:
x = np.array([1,3])
x

array([1, 3])

In [9]:
print(x)  

[1 3]


In [11]:
type(x) # sprawdzenie typu zmiennej

numpy.ndarray

In [12]:
x.ndim #wymiar tablicy

1

In [14]:
x.shape #kształt tablicy

(2,)

In [15]:
x.size #liczba elementów tablicy

2

In [17]:
x.dtype #typ danych (ile miejsca zajmują w pamięci?)

dtype('int64')

Liczby zmiennoprzecinkowe

In [19]:
x = np.array([1.3,2.3,1.4])
print(x)

[1.3 2.3 1.4]


In [20]:
x.dtype

dtype('float64')

**2D array**


In [22]:
x = np.array([[1,2],[-3,1]])

In [ ]:
x.ndim

In [ ]:
x.shape

In [ ]:
x.dtype

In [28]:
x = np.array([[1,2,4],[4,2,1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [ ]:
x.ndim

In [ ]:
x.shape

3D Array

In [41]:
x = np.array(
   [
    [
     [4,3,1],
     [3,1,2]
     ],
     [
      [4,1,3],
      [4,2,1]
      ],
      [
      [4,1,3],
      [4,2,1]
      ]
    ])
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [42]:
x.ndim

3

In [43]:
x.shape

(3, 2, 3)

**Typy danych**


In [44]:
A = np.array([1,2,3])
A.dtype

dtype('int64')

In [49]:
A = np.array([1.,2.7,3.])
A.dtype

dtype('float64')

In [48]:
A = np.array([1,2,3], dtype='complex')
A

array([1.+0.j, 2.+0.j, 3.+0.j])

In [51]:
A = np.array([True, False])
A.dtype

dtype('bool')

**Tworzenie tablicy**


In [58]:
np.zeros(shape=(4,10), dtype='int') #wypełnij 0    

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [59]:
np.ones(shape=(5,5),dtype='complex') # wypełnij 1 

array([[1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j]])

In [60]:
np.full(shape=(3,3), fill_value=4,dtype="int") #wypełnij 4 (dowolną wartością)

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [62]:
 np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
np.arange(start=5,stop=10, step=2)

array([5, 7, 9])

In [69]:
np.linspace(start=0,stop=1,num=5) #równo rozkłada przedział na liczbę elementów

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [70]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [74]:
A.reshape((-1,5)) # zmienia rozmiar tablicy

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

**Operacje na tablicach**

In [75]:
A = np.array([3,1,4,2])
B = np.array([3,-1,3,2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [ ]:
A + B


In [ ]:
A - B

In [79]:
A * B #Ax * Bx, Ay * By ...

array([ 9, -1, 12,  4])

In [81]:
A/B # po dzieleniu jest float

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [82]:
A + 3 #dodanie stałej do każdeego elementu

array([6, 4, 7, 5])

In [83]:
2 * A 

array([6, 2, 8, 4])

In [87]:
np.add(A,B)

array([6, 0, 7, 4])

Mnożenie macierzowe 

In [91]:
X = np.array([[1,3],[-2,0]]) 
Y = np.array([[6,0],[-1,2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [92]:
np.dot(X,Y)

array([[  3,   6],
       [-12,   0]])

Generowanie liczb pseudolowosych

In [93]:
np.random.seed(0) #ustalenie ziarna losowania 

In [94]:
np.random.randn() #losowa wartość z rozkładu normalnego 

1.764052345967664

In [95]:
np.random.randn(10) #10 wartości losowych z rozkładu normalnego 

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [98]:
np.random.randn(10,4) #do utworzenia histogramu rozkładu normalnego; wartości utożsamiane jako 10 (liczba próbek), 4 (liczba zmiennych)

array([[ 1.22244507,  0.20827498,  0.97663904,  0.3563664 ],
       [ 0.70657317,  0.01050002,  1.78587049,  0.12691209],
       [ 0.40198936,  1.8831507 , -1.34775906, -1.270485  ],
       [ 0.96939671, -1.17312341,  1.94362119, -0.41361898],
       [-0.74745481,  1.92294203,  1.48051479,  1.86755896],
       [ 0.90604466, -0.86122569,  1.91006495, -0.26800337],
       [ 0.8024564 ,  0.94725197, -0.15501009,  0.61407937],
       [ 0.92220667,  0.37642553, -1.09940079,  0.29823817],
       [ 1.3263859 , -0.69456786, -0.14963454, -0.43515355],
       [ 1.84926373,  0.67229476,  0.40746184, -0.76991607]])

In [99]:
np.random.rand() # wartość losowa z przedziału [0,1) - rozkład jednostajny

0.5210366062041293

In [100]:
np.random.randint(10) #liczba całkowita mniejsza niż 10 

1