<a href="https://colab.research.google.com/github/nefetorve/big_data/blob/master/07_uczenie_glebokie/02_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
%tensorflow_version 2.x
import tensorflow as tf
import numpy as np 
import pandas as pd 
import plotly.express as px 
tf.__version__

'2.3.0'

In [18]:
from tensorflow.keras.models import Sequential 

model = Sequential()
print(model)

In [19]:
from tensorflow.keras.layers import Dense
model.add(Dense(units=4, input_shape=(10,))) # units - liczba neuronów

In [20]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 4)                 44        
Total params: 44
Trainable params: 44
Non-trainable params: 0
_________________________________________________________________


In [21]:
model.add(Dense(units=2))

model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 4)                 44        
_________________________________________________________________
dense_5 (Dense)              (None, 2)                 10        
Total params: 54
Trainable params: 54
Non-trainable params: 0
_________________________________________________________________


In [22]:
from tensorflow.keras.activations import linear 


random_data = np.linspace(start=-3, stop=3, num=300)
data = pd.DataFrame({'data': random_data, 'linear': linear(random_data)})
data.head()

data    linear
0 -3.000000 -3.000000
1 -2.979933 -2.979933
2 -2.959866 -2.959866
3 -2.939799 -2.939799
4 -2.919732 -2.919732

In [23]:
px.line(data, x='data', y='linear', width=500, height=400, range_y=[-3,3])

In [24]:
from tensorflow.keras.activations import sigmoid
from tensorflow.keras.activations import relu
data = pd.DataFrame({'data': random_data, 'sigmoid': sigmoid(random_data)})
data.head()

data   sigmoid
0 -3.000000  0.047426
1 -2.979933  0.048341
2 -2.959866  0.049272
3 -2.939799  0.050221
4 -2.919732  0.051187

In [25]:
px.line(data, x='data', y='sigmoid', width=500, height=400, range_y=[-0.5,1.5])

In [26]:
model = Sequential()
model.add(Dense(units=8, activation='relu', input_shape=(10,)))
model.add(Dense(units=1, activation='sigmoid'))

model.summary()


Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 8)                 88        
_________________________________________________________________
dense_7 (Dense)              (None, 1)                 9         
Total params: 97
Trainable params: 97
Non-trainable params: 0
_________________________________________________________________


In [27]:
model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [28]:
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [29]:
model.compile(optimizer='rmsprop',
              loss='mse')

In [30]:
data = np.random.randn(10000, 150)
labels = np.random.randint(2,size=(10000,1))

print(data.shape)
print(labels.shape)

(10000, 150)
(10000, 1)


In [31]:
model = Sequential()
model.add(Dense(units=32,activation='relu',input_shape=(150,)))
model.add(Dense(1,activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data,labels,epochs=20)

Epoch 1/20
313/313 [==============================] - 1s 2ms/step - loss: 0.7457 - accuracy: 0.5009
Epoch 2/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6911 - accuracy: 0.5525
Epoch 3/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6722 - accuracy: 0.5841
Epoch 4/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6576 - accuracy: 0.6111
Epoch 5/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6439 - accuracy: 0.6323
Epoch 6/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6297 - accuracy: 0.6474
Epoch 7/20
313/313 [==============================] - 0s 997us/step - loss: 0.6152 - accuracy: 0.6657
Epoch 8/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6016 - accuracy: 0.6780
Epoch 9/20
313/313 [==============================] - 0s 1ms/step - loss: 0.5879 - accuracy: 0.6931
Epoch 10/20
313/313 [==============================] - 0s 1ms/step - loss: 0.5754 - accuracy: 0.70

In [32]:
model = Sequential()
model.add(Dense(units=32,activation='relu',input_shape=(150,)))
model.add(Dense(1,activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data,labels,epochs=20, batch_size=64)

Epoch 1/20
157/157 [==============================] - 0s 1ms/step - loss: 0.7565 - accuracy: 0.5015
Epoch 2/20
157/157 [==============================] - 0s 1ms/step - loss: 0.7014 - accuracy: 0.5400
Epoch 3/20
157/157 [==============================] - 0s 1ms/step - loss: 0.6824 - accuracy: 0.5697
Epoch 4/20
157/157 [==============================] - 0s 1ms/step - loss: 0.6692 - accuracy: 0.5965
Epoch 5/20
157/157 [==============================] - 0s 1ms/step - loss: 0.6575 - accuracy: 0.6116
Epoch 6/20
157/157 [==============================] - 0s 1ms/step - loss: 0.6469 - accuracy: 0.6261
Epoch 7/20
157/157 [==============================] - 0s 1ms/step - loss: 0.6361 - accuracy: 0.6470
Epoch 8/20
157/157 [==============================] - 0s 1ms/step - loss: 0.6252 - accuracy: 0.6641
Epoch 9/20
157/157 [==============================] - 0s 1ms/step - loss: 0.6142 - accuracy: 0.6702
Epoch 10/20
157/157 [==============================] - 0s 1ms/step - loss: 0.6033 - accuracy: 0.6863

In [33]:
model = Sequential()
model.add(Dense(units=32,activation='relu',input_shape=(150,)))
model.add(Dense(1,activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data,labels,epochs=20, validation_split=0.2)

Epoch 1/20
250/250 [==============================] - 0s 2ms/step - loss: 0.7503 - accuracy: 0.5034 - val_loss: 0.7110 - val_accuracy: 0.5260
Epoch 2/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6905 - accuracy: 0.5526 - val_loss: 0.7102 - val_accuracy: 0.5185
Epoch 3/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6705 - accuracy: 0.5919 - val_loss: 0.7146 - val_accuracy: 0.5195
Epoch 4/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6554 - accuracy: 0.6114 - val_loss: 0.7197 - val_accuracy: 0.5160
Epoch 5/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6414 - accuracy: 0.6349 - val_loss: 0.7237 - val_accuracy: 0.5165
Epoch 6/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6262 - accuracy: 0.6607 - val_loss: 0.7294 - val_accuracy: 0.5125
Epoch 7/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6106 - accuracy: 0.6755 - val_loss: 0.7386 - val_accuracy: 0.5135
Epoch 

In [37]:
model = Sequential()
model.add(Dense(units=32,activation='relu',input_shape=(150,)))
model.add(Dense(1,activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(data,labels,epochs=20, validation_split=0.2, verbose=0)

In [38]:
history

In [39]:
metrics = history.history
metrics.keys()

dict_keys(['loss', 'accuracy', 'val_loss', 'val_accuracy'])

In [40]:
test_data = np.random.randn(5,150)
test_labels = np.random.randint(2,size=(5,1))

In [42]:
model.predict(test_data)

array([[0.2988343 ],
       [0.853883  ],
       [0.42048705],
       [0.4744254 ],
       [0.68657917]], dtype=float32)

In [43]:
model.predict_proba(test_data)

Instructions for updating:
Please use `model.predict()` instead.


array([[0.2988343 ],
       [0.853883  ],
       [0.42048705],
       [0.4744254 ],
       [0.68657917]], dtype=float32)

In [44]:
model.predict_classes(test_data)

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


array([[0],
       [1],
       [0],
       [0],
       [1]], dtype=int32)

In [45]:
data = np.random.randn(10000, 150)
labels = np.random.randint(10,size=(10000,1))


In [48]:
print(data.shape)
print(labels.shape)

(10000, 150)
(10000, 10)


In [47]:
from tensorflow.keras.utils import to_categorical
labels = to_categorical(labels, num_classes=10)
labels

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [51]:
labels[1]

array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0.], dtype=float32)

In [52]:
model = Sequential()
model.add(Dense(units=32,activation='relu',input_shape=(150,)))
model.add(Dense(10,activation='softmax'))

model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

history = model.fit(data,labels,epochs=20, validation_split=0.2)

Epoch 1/20
250/250 [==============================] - 0s 2ms/step - loss: 2.5301 - accuracy: 0.0951 - val_loss: 2.4658 - val_accuracy: 0.0945
Epoch 2/20
250/250 [==============================] - 0s 1ms/step - loss: 2.3448 - accuracy: 0.1198 - val_loss: 2.4165 - val_accuracy: 0.0925
Epoch 3/20
250/250 [==============================] - 0s 1ms/step - loss: 2.2745 - accuracy: 0.1554 - val_loss: 2.4068 - val_accuracy: 0.0840
Epoch 4/20
250/250 [==============================] - 0s 1ms/step - loss: 2.2341 - accuracy: 0.1709 - val_loss: 2.4094 - val_accuracy: 0.0865
Epoch 5/20
250/250 [==============================] - 0s 1ms/step - loss: 2.2066 - accuracy: 0.1879 - val_loss: 2.4210 - val_accuracy: 0.0865
Epoch 6/20
250/250 [==============================] - 0s 1ms/step - loss: 2.1840 - accuracy: 0.2009 - val_loss: 2.4293 - val_accuracy: 0.0940
Epoch 7/20
250/250 [==============================] - 0s 1ms/step - loss: 2.1627 - accuracy: 0.2099 - val_loss: 2.4448 - val_accuracy: 0.0865
Epoch 

In [53]:
test_data = np.random.random((10,150))

model.predict(test_data)

array([[0.14804769, 0.04021834, 0.08481501, 0.2316031 , 0.05996776,
        0.04945217, 0.09920873, 0.07742861, 0.05514962, 0.15410891],
       [0.16633072, 0.04903917, 0.10432848, 0.15611915, 0.06615189,
        0.04189235, 0.1252934 , 0.06300395, 0.04926849, 0.17857236],
       [0.14594533, 0.0611272 , 0.11992531, 0.12386118, 0.08481588,
        0.09352057, 0.11401249, 0.06303503, 0.0585796 , 0.13517746],
       [0.16728748, 0.05327214, 0.11181342, 0.12496804, 0.07491296,
        0.07171918, 0.14231461, 0.06675323, 0.07331406, 0.11364492],
       [0.1294621 , 0.06326494, 0.09144145, 0.11893304, 0.0922107 ,
        0.04858819, 0.10988072, 0.09933712, 0.10056861, 0.14631307],
       [0.14538473, 0.07724215, 0.08477866, 0.07977251, 0.08797012,
        0.05416695, 0.12779678, 0.1327745 , 0.09947024, 0.11064336],
       [0.17458802, 0.04530762, 0.10089521, 0.15100648, 0.08393709,
        0.03663316, 0.13748947, 0.07021353, 0.06375039, 0.13617915],
       [0.13790031, 0.06895154, 0.1303262

In [54]:
model.predict_classes(test_data)

array([3, 9, 0, 0, 9, 0, 0, 0, 3, 0])

In [55]:
data = np.random.random((10000,150))
labels = 50 * np.random.random(10000)


In [56]:
labels[:10]

array([ 9.69752821,  2.5048946 , 16.86650625,  1.45044826,  8.78411065,
       37.56158657, 37.79562119,  2.59035992, 46.28237403, 31.74028349])

In [57]:
model = Sequential()
model.add(Dense(units=32,activation='relu',input_shape=(150,)))
model.add(Dense(units=1))

model.compile(optimizer='rmsprop',
              loss='mse')
history = model.fit(data,labels,epochs=30, batch_size=32, validation_split=0.2)

Epoch 1/30
250/250 [==============================] - 0s 1ms/step - loss: 286.7577 - val_loss: 207.3881
Epoch 2/30
250/250 [==============================] - 0s 1ms/step - loss: 211.4411 - val_loss: 207.9375
Epoch 3/30
250/250 [==============================] - 0s 1ms/step - loss: 211.1117 - val_loss: 207.5410
Epoch 4/30
250/250 [==============================] - 0s 1ms/step - loss: 210.6122 - val_loss: 208.1087
Epoch 5/30
250/250 [==============================] - 0s 1ms/step - loss: 210.4418 - val_loss: 208.0003
Epoch 6/30
250/250 [==============================] - 0s 1ms/step - loss: 209.9102 - val_loss: 209.4204
Epoch 7/30
250/250 [==============================] - 0s 1ms/step - loss: 209.3463 - val_loss: 208.1542
Epoch 8/30
250/250 [==============================] - 0s 1ms/step - loss: 209.2502 - val_loss: 208.1490
Epoch 9/30
250/250 [==============================] - 0s 1ms/step - loss: 208.9521 - val_loss: 208.6501
Epoch 10/30
250/250 [==============================] - 0s 1ms/st

In [58]:
model = Sequential()
model.add(Dense(units=32,activation='relu',input_shape=(150,)))
model.add(Dense(units=1))

model.compile(optimizer='rmsprop',
              loss='mae',
              metrics=["mse"])
history = model.fit(data,labels,epochs=30, batch_size=32, validation_split=0.2)

Epoch 1/30
250/250 [==============================] - 0s 2ms/step - loss: 13.4421 - mse: 253.1333 - val_loss: 12.3881 - val_mse: 206.7337
Epoch 2/30
250/250 [==============================] - 0s 1ms/step - loss: 12.5839 - mse: 211.5176 - val_loss: 12.5552 - val_mse: 211.8281
Epoch 3/30
250/250 [==============================] - 0s 1ms/step - loss: 12.5613 - mse: 211.1090 - val_loss: 12.3946 - val_mse: 208.1017
Epoch 4/30
250/250 [==============================] - 0s 1ms/step - loss: 12.5536 - mse: 210.9876 - val_loss: 12.3994 - val_mse: 207.4683
Epoch 5/30
250/250 [==============================] - 0s 1ms/step - loss: 12.5351 - mse: 210.5998 - val_loss: 12.4107 - val_mse: 208.9741
Epoch 6/30
250/250 [==============================] - 0s 1ms/step - loss: 12.5264 - mse: 210.0123 - val_loss: 12.4542 - val_mse: 208.6839
Epoch 7/30
250/250 [==============================] - 0s 1ms/step - loss: 12.4952 - mse: 209.8209 - val_loss: 12.5145 - val_mse: 210.7392
Epoch 8/30
250/250 [==============

In [59]:
test_data = np.random.random((10,150))

model.predict(test_data)

array([[19.992422],
       [31.43556 ],
       [21.895948],
       [28.46148 ],
       [25.775452],
       [29.077463],
       [21.289461],
       [24.289553],
       [25.194576],
       [28.429605]], dtype=float32)